import Foundation
import Commander
import RingRingCore

/// RingRing CLI - phone call automation
@MainActor
public struct PhoneCallCLI {
    private let manager = CallManager()

    public init() {}

    /// Execute CLI with given arguments
    public func run(arguments: [String]) async throws {
        // Try MCP mode first (no arguments or explicit mcp command)
        if arguments.count <= 1 || (arguments.count > 1 && arguments[1] == "mcp") {
            try await runMCPMode()
            return
        }

        // CLI mode
        let command = arguments.count > 1 ? arguments[1] : ""

        switch command {
        case "init":
            try await runInitCommand()
        case "call":
            try await runCallCommand(arguments: Array(arguments.dropFirst(2)))
        case "status":
            try await runStatusCommand()
        case "webhook":
            try await runWebhookCommand(arguments: Array(arguments.dropFirst(2)))
        case "help", "--help", "-h":
            showHelp()
        default:
            print("Unknown command: \(command)")
            showHelp()
        }
    }

    private func runMCPMode() async throws {
        // Load configuration
        let config = try await Configuration.shared.loadFromEnvironment()

        // Initialize manager
        try await manager.initialize(config)

        // Create and run MCP server
        let mcp = PhoneCallMCP(manager: manager)
        try await mcp.run()
    }

    private func runInitCommand() async throws {
        print("""
        📞 RingRing Interactive Setup
        ==============================

        This will help you configure RingRing for making phone calls.
        """)

        print("\nChoose your phone provider:")
        print("  1. Telnyx (recommended - ~50% cheaper)")
        print("  2. Twilio")

        let providerChoice = readLine()?.trimmingCharacters(in: .whitespaces) ?? "1"
        let provider = providerChoice == "2" ? "twilio" : "telnyx"

        print("\n--- Provider Setup (\(provider.uppercased())) ---")
        print("Enter your API credentials:")
        print("(Get these from your \(provider == "telnyx" ? "Telnyx Portal" : "Twilio Console"))")

        print("\nAccount SID / Connection ID:")
        let accountSid = readLine()?.trimmingCharacters(in: .whitespaces) ?? ""

        print("\nAuth Token / API Key:")
        let authToken = readLine()?.trimmingCharacters(in: .whitespaces) ?? ""

        print("\nYour Phone Number (the one the AI will call FROM):")
        let phoneNumber = readLine()?.trimmingCharacters(in: .whitespaces) ?? ""

        print("\nUser Phone Number (the one to call TO - your number):")
        let userPhoneNumber = readLine()?.trimmingCharacters(in: .whitespaces) ?? ""

        print("\n--- OpenAI API Setup ---")
        print("Enter your OpenAI API Key:")
        let openAIApiKey = readLine()?.trimmingCharacters(in: .whitespaces) ?? ""

        print("\n--- ngrok Setup ---")
        print("Enter your ngrok auth token (leave blank to skip):")
        let ngrokAuthToken = readLine()?.trimmingCharacters(in: .whitespaces)

        // Generate environment file
        let envContent = """
        # RingRing Configuration
        # Generated by: phonecall init

        # Phone Provider Configuration
        CALLME_PHONE_PROVIDER=\(provider)
        CALLME_PHONE_ACCOUNT_SID=\(accountSid)
        CALLME_PHONE_AUTH_TOKEN=\(authToken)
        CALLME_PHONE_NUMBER=\(phoneNumber)
        CALLME_USER_PHONE_NUMBER=\(userPhoneNumber)

        # OpenAI Configuration
        CALLME_OPENAI_API_KEY=\(openAIApiKey)
        CALLME_TTS_VOICE=onyx

        # ngrok Configuration
        CALLME_NGROK_AUTHTOKEN=\(ngrokAuthToken ?? "")
        CALLME_PORT=3333

        # Call Configuration
        CALLME_TRANSCRIPT_TIMEOUT_MS=180000
        CALLME_STT_SILENCE_DURATION_MS=800
        """

        print("\n\n--- Configuration Generated ---")
        print("Add this to your environment (.zshrc, .bashrc, or Claude settings):")
        print("\n" + String(repeating: "=", count: 50))
        print(envContent)
        print(String(repeating: "=", count: 50))

        print("\n\n✅ Setup complete!")
        print("\nQuick start:")
        print("  1. Export the environment variables above")
        print("  2. Run: phonecall call \"Hello, I have a question\"")
        print("  3. Or use as MCP: phonecall mcp")
    }

    private func runCallCommand(arguments: [String]) async throws {
        let message = arguments.first ?? ""
        guard !message.isEmpty else {
            print("Error: Message required")
            print("Usage: phonecall call \"your message\"")
            return
        }

        // Load configuration
        let config = try await Configuration.shared.loadFromEnvironment()

        // Initialize manager
        try await manager.initialize(config)

        print("📞 Initiating call...")
        let result = try await manager.initiateCall(message: message)

        print("\n✅ Call connected!")
        print("   Call ID: \(result.callId)")
        print("   User said: \(result.response)")

        // Simple interactive loop
        print("\n--- Interactive Mode ---")
        print("Type your next message (or 'quit' to hang up):")

        while true {
            guard let input = readLine()?.trimmingCharacters(in: .whitespaces) else {
                break
            }

            if input == "quit" || input == "exit" || input == "q" {
                try await manager.endCall(callId: result.callId, message: "Goodbye!")
                print("\n👋 Call ended.")
                break
            }

            let response = try await manager.continueCall(callId: result.callId, message: input)
            print("   User said: \(response)")
            print("\n> ", terminator: "")
        }

        // Shutdown
        await manager.shutdown()
    }

    private func runStatusCommand() async throws {
        print("📞 RingRing Status")
        print("=================")

        // Check configuration
        do {
            let config = try await Configuration.shared.loadFromEnvironment()
            print("\n✅ Configuration loaded:")
            print("   Provider: \(config.phone.provider.rawValue)")
            print("   Phone Number: \(config.phone.phoneNumber)")
            print("   User Number: \(config.userPhoneNumber)")
            print("   TTS Voice: \(config.tts.voice.rawValue)")
        } catch {
            print("\n❌ Configuration error: \(error.localizedDescription)")
            print("\nRun 'phonecall init' to set up configuration.")
        }

        // Check ngrok (if available)
        print("\n📡 Checking ngrok...")
        let ngrokCheck = shell("/usr/local/bin/ngrok version")
        if !ngrokCheck.isEmpty {
            print("   ✅ ngrok installed")
        } else {
            print("   ⚠️  ngrok not found (optional)")
        }
    }

    private func runWebhookCommand(arguments: [String]) async throws {
        guard let action = arguments.first else {
            print("Usage: phonecall webhook [start|stop]")
            return
        }

        switch action {
        case "start":
            try await startWebhookServer()
        case "stop":
            print("To stop the webhook server, press Ctrl+C")
        default:
            print("Unknown action: \(action)")
            print("Usage: phonecall webhook [start|stop]")
        }
    }

    private func startWebhookServer() async throws {
        print("🌐 Starting webhook server...")

        // Load configuration
        let config = try await Configuration.shared.loadFromEnvironment()

        // Initialize manager
        try await manager.initialize(config)

        // Start server
        try await manager.startServer()

        print("\n✅ Server listening on port \(config.webhook.port)")
        print("\nWebhook URL: \(config.webhook.publicUrl)/twiml")
        print("\nPress Ctrl+C to stop")

        // Keep running
        signal(SIGINT) { _ in
            print("\n\nShutting down...")
            Task {
                await self.manager.shutdown()
                exit(0)
            }
        }

        // Run indefinitely
        RunLoop.current.run()
    }

    private func showHelp() {
        print("""
        📞 RingRing - Let AI call you on the phone

        USAGE:
            phonecall [command] [arguments]

        COMMANDS:
            mcp                    Run as MCP server (default)
            init                   Interactive setup wizard
            call <message>         Make a call with a message
            status                 Check configuration status
            webhook start          Start webhook server
            help                   Show this help message

        EXAMPLES:
            phonecall init                     # Set up configuration
            phonecall call "I finished the task"  # Make a call
            phonecall status                   # Check status
            phonecall mcp                      # Run as MCP server

        ENVIRONMENT:
            CALLME_PHONE_PROVIDER         Phone provider (telnyx/twilio)
            CALLME_PHONE_ACCOUNT_SID      Account SID or Connection ID
            CALLME_PHONE_AUTH_TOKEN       Auth Token or API Key
            CALLME_PHONE_NUMBER           Phone number to call FROM
            CALLME_USER_PHONE_NUMBER      Phone number to call TO
            CALLME_OPENAI_API_KEY         OpenAI API key

        For more information, visit: https://github.com/RyanLisse/RingRing
        """)
    }

    private func shell(_ command: String) -> String {
        let pipe = Pipe()
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/bash")
        process.arguments = ["-c", command]
        process.standardOutput = pipe

        do {
            try process.run()
            let data = pipe.fileHandleForReading.readDataToEndOfFile()
            return String(data: data, encoding: .utf8) ?? ""
        } catch {
            return ""
        }
    }
}
